[Feat] 멤버 회원가입
NHN-BookPub/bookpub-shop pull request #13
Opened 2023-01-06 13:48 UTC by limtaewon

front에서 멤버 정보 받아 db에 저장

2023-01-06 13:58 UTC, uasaha approved these changes

2023-01-06 13:58 UTC, uasaha commented on src/main/java/com/nhnacademy/bookpubshop/member/dto/MemberSignupResponse.java
> +public class MemberSignupResponse implements Serializable {
클래스 이름에 Dto 빠졌습니다~~

2023-01-06 13:58 UTC, uasaha commented on src/main/java/com/nhnacademy/bookpubshop/tier/exception/NotFoundTierException.java
> +        super("존재하지 않는 등급입니다.");
Exception 정보에 어떤 등급인지도 같이 띄워주면 좋을 것 같아요

2023-01-06 13:58 UTC, unhas01 commented on src/main/java/com/nhnacademy/bookpubshop/member/dto/MemberSignupResponse.java
> +public class MemberSignupResponse implements Serializable {
DTO명 규칙
[행위] + [객체] + [Response/Request] + Dto
이 부분 수정해주세요

2023-01-06 13:59 UTC, unhas01 commented on src/main/java/com/nhnacademy/bookpubshop/tier/exception/NotFoundTierException.java
> +    }
super() 생성자로 메세지도 남겨주면 좋을 것 같습니다.
ex) super("존재하지 않는 등급 : ", "다이아몬드");

2023-01-06 14:00 UTC, unhas01 approved these changes

2023-01-06 14:07 UTC, hobby3530 approved these changes
수고하셨습니다!

2023-01-06 14:12 UTC, HoFe-U requested changes
Feat 을 작성한 이후에 PR 을 올리는게 아니라 전체 API 생성이후에 올리면 감사하겠습니다.
수정하신후에 approve 하겠습니다.

2023-01-06 14:12 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/member/controller/MemberController.java
> +        MultiValueMap<String, String> memberInfo = new LinkedMultiValueMap<>();
ResponseEntity -> '?' 와일드카드를 굳이 넣어야할까요?

2023-01-06 14:12 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/member/dto/MemberSignupResponse.java
> +
닉네임에도 특수문제 제약을 넣어야할것같습니다.

2023-01-06 14:12 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/member/entity/Member.java
> +        this.memberName = memberName;
이름 길어지면 체크스타일 에러나지않던가요? 엔터한번 넣어주시죠 ㅎㅎ

2023-01-06 14:12 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/tier/exception/NotFoundTierException.java
> +        super("존재하지 않는 등급입니다.");
Message 를 private static final 로 구분하는건 어떨까요? 
그리고 NotFound 에서는 존재하지않은 등급만 보여주는것도 괜찮을것같습니다만. 다른 exception 을 띄울때는 메세지를 첨부하는것도 좋은 방법인것같습니다.

2023-01-06 14:59 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubshop/member/controller/MemberController.java
> +        MultiValueMap<String, String> memberInfo = new LinkedMultiValueMap<>();
타입 이것저것 실험해 보다 깜빡하고 안바꿨네용 수정완료했습니다!

2023-01-06 14:59 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubshop/member/dto/MemberSignupResponse.java
> +
추가했습니다

2023-01-06 15:00 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubshop/member/entity/Member.java
> +        this.memberName = memberName;
네 변경완료했습니다

2023-01-06 15:00 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubshop/tier/exception/NotFoundTierException.java
> +        super("존재하지 않는 등급입니다.");
잘 모르는 부분이라 내일 예시확인 후 적용해보겠습니다.

2023-01-09 01:09 UTC, HoFe-U approved these changes
수고하셨습니다.

행위 검증이랑 체크하신부분만 수정하면 될것같습니다.

2023-01-09 01:09 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/member/controller/MemberController.java
> +        );
여기서 dto 를 new 를 왜해야할까요? 
String defaultTier 라는 값도 왜 Controller 에 있어야하죠?

2023-01-09 01:09 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/member/service/MemberService.java
> +
duplicationCheck 에다가 Dto 를 넣으면 안되나요? 변수값을 따로 받을 이유가있을까요?

2023-01-09 01:23 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubshop/member/controller/MemberController.java
> +        );
서비스에 있는게 맞는것 같아 변경완료했습니다!

2023-01-09 01:23 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubshop/member/service/MemberService.java
> +
Dto로 넣는게 맞는거 같아 변경했습니다!

2023-01-09 01:27 UTC, merged

2023-01-09 01:27 UTC, uasaha approved these changes

2023-01-09 01:34 UTC, seohyeon07 approved these changes
수고하셨습니다!