Feature/order
NHN-BookPub/bookpub-shop pull request #46
Opened 2023-01-18 14:12 UTC by uasaha

2023-01-18 14:58 UTC, HoFe-U requested changes
수고하셨습니다.
적힌사항들 수정부탁드리겠습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/address/exception/AddressNotFoundException.java
> +}
public final static 으로 처리하면 message 를 바로 받아서 처리할 수 있을것같습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/order/controller/OrderController.java
> +    /**
request param 으로 member no 를 받은 이유가있을까요?

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/order/dto/GetOrderDetailResponseDto.java
> +
이부분의 data 가 product 의 데이터인것같은데 전체생성자를 처리하지않고 이렇게 적으신 이유가있을까요?

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/order/exception/OrderNotFoundException.java
> +}
public 타입으로 해서 예외를 읽으면 좋을것같습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/order/relationship/controller/OrderProductStateCodeController.java
> +     *
order Product <- 이부분 이 수정되어야할것같습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/order/relationship/dto/CreateOrderProductStateCodeRequestDto.java
> +}
validation 부분이 빠진것같습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/order/relationship/service/impl/OrderProductStateCodeServiceImpl.java
> +}
@Transcation 이 빠져있습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/order/repository/impl/OrderRepositoryImpl.java
> +                        order.orderPrice
java doc 이 빠져있습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/order/service/impl/OrderServiceImpl.java
> +    @Override
@Transcational 이뻐져있스빈다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/orderstatecode/controller/OrderStateCodeController.java
> +
Api 작성법을 참고해서 하시면 좋을것같습니다. 
명사를 사용하고 복수형을 적되, 대문자를 넣지않습니다. 명사 + 명사를 적어야할경우는 order-state 가 될것같습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/orderstatecode/service/impl/OrderStateCodeServiceImpl.java
> +     */
@Transactional 이빠져있습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/pricepolicy/controller/PricePolicyController.java
> +     * 모든 가격 정책을 반환합니다.
api 수정부탁드립니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/pricepolicy/controller/PricePolicyController.java
> +}
이부분 getMapping 에 / 가 없는데 작동하나요?

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/pricepolicy/dto/GetPricePolicyResponseDto.java
> +@Getter
doc 빠졌습니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/pricepolicy/exception/NotFoundPricePolicyException.java
> +        super(MESSAGE);
public 으로 변경부탁드립니다.

2023-01-18 14:58 UTC, HoFe-U commented on src/main/java/com/nhnacademy/bookpubshop/pricepolicy/service/impl/PricePolicyServiceImpl.java
> +    /**
@Transcational 이 빠져있습니다.

2023-01-19 00:11 UTC, uasaha commented on src/main/java/com/nhnacademy/bookpubshop/order/dto/GetOrderDetailResponseDto.java
> +
querydsl 사용중 Projections.constructor에서 하나의 필드가 다른 엔티티의 Dto입니다. 이 리스트를 받아오기 위한 서브쿼리는 지원되지 않아 그것을 제외한 생성자를 적용하였습니다.

2023-01-19 00:27 UTC, uasaha commented on src/main/java/com/nhnacademy/bookpubshop/order/controller/OrderController.java
> +    /**
일단 프론트 서버에 맡기는 형식으로 제작되었는데, 추후 수정예정입니다.

2023-01-19 00:31 UTC, uasaha commented on src/main/java/com/nhnacademy/bookpubshop/pricepolicy/service/impl/PricePolicyServiceImpl.java
> +    /**
전체적으로 수정완료했습니다.

2023-01-19 04:17 UTC, limtaewon approved these changes
수고하셨습니다

2023-01-19 04:17 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubshop/order/dto/CreateOrderRequestDto.java
> +    private Map<Long, String> orderProductReasons;
map 자료구조를 사용 할 일이 있나요?

2023-01-19 04:17 UTC, limtaewon commented on src/main/java/com/nhnacademy/bookpubshop/order/relationship/service/impl/OrderProductStateCodeServiceImpl.java
> +@RequiredArgsConstructor
@Transactional 빠졌습니당

2023-01-19 06:37 UTC, nhn-academy-marco reviewed
수고하셨습니다.
다만.. 어마어마한 commit으로 팀원들간 코드리뷰가 힘들었을 것으로 보입니다.
dooray todo 단위로 분리해서 관리하시는게 좋을거 같네요.

2023-01-19 06:37 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubshop/order/entity/BookpubOrder.java
>      @JoinColumn(name = "price_policy_packaging_number")
@ManyToOne 사용하실때 fetch type default  즉시로딩 일텐데..
의도하신건가요? 의도하지 않았다면 lazy를 사용하고 개발하는 과정에서 필요할 때 eagger 변경해보는건 어떨까요.
즉시로딩의 특성상 의도하지 안은 쿼리가 발생할 수 있습니다.

2023-01-19 06:37 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubshop/order/entity/BookpubOrder.java
> +@Builder
@Builder entity 레벨에서 지정하기 보다는 method level에서 지정해보시는건 어떨까요?

2023-01-19 06:37 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubshop/order/relationship/entity/OrderProductStateCode.java
> +    public void modifyUsed() {
modifyUsed를 통해서 반대로 boolean값을 지정하고 있네요.
해당 method를 호출하는쪽 로직에서 설정하려고하는 true/false값을 명확하게 처리해보는건 어떨까요?
codeUsed에 값에 의존해서 반대로 설정하는 상황으로 보이는데.. 상황에 따라서 잘못 설정될 수 있어요..
예를들어 예기치 못하게 2번 호출된다면?...

2023-01-19 06:37 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubshop/order/repository/impl/OrderRepositoryImpl.java
> +                .join(product).on(orderProduct.product.productNo.eq(product.productNo))
product , orderProduct  연관관계가 entity에 설정되어 있다면
on 생략가능합니다.

2023-01-19 06:37 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/bookpubshop/pricepolicy/repository/impl/PricePolicyRepositoryImpl.java
> +                .fetchOne());
fetchOne 과 limit(1)을 동시에 사용한 이유가 있을까요?

2023-01-19 06:44 UTC, HoFe-U approved these changes
수고하셨습니다.

2023-01-19 06:57 UTC, uasaha commented on src/main/java/com/nhnacademy/bookpubshop/pricepolicy/repository/impl/PricePolicyRepositoryImpl.java
> +                .fetchOne());
리뷰 감사합니다
모든 리뷰 사항들 적용하여 수정하였습니다!

2023-01-19 07:05 UTC, merged