Feature/api docs sh
NHN-BookPub/bookpub-shop pull request #63
Opened 2023-01-26 02:33 UTC by seohyeon07

rest api docs 작성 완료했습니다.

2023-01-26 03:36 UTC, unhas01 reviewed
.adoc 파일이 없습니다.

2023-01-26 03:36 UTC, unhas01 commented on src/main/java/com/nhnacademy/bookpubshop/order/dto/CreateOrderRequestDto.java
> +    @NotBlank(message = "상품 번호 필수 입력사항입니다.")
List도 validation이 적용이 되나요??

2023-01-26 04:36 UTC, hobby3530 commented on src/main/java/com/nhnacademy/bookpubshop/order/dto/CreateOrderRequestDto.java
> +    @NotBlank(message = "도로명 주소는 필수 입력사항입니다.")
길이 제한 어노테이션은 없나요?

2023-01-26 04:38 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                        .content(mapper.writeValueAsString(new PageResponse<>(pages))))
page와 size는 url에 박아넣는것보다 param으로 빼서 테스트하는 게 나아보입니다!

2023-01-26 04:38 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                        responseFields(
rest docs 작업하실때도 페이지 param 정보를 넣어주시면 좋을 것 같습니다.

2023-01-26 04:39 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                                                .description("사유 명"),
PayloadDocumentation은 어떤 역할을 하나요?

2023-01-26 04:40 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                ));
이부분도 url에 param을 넣는것보다 따로 param으로 빼서 처리하는게 좋을것 같습니다.

2023-01-26 04:41 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                                parameterWithName("orderNo").description("주문 번호"))));
이부분도 마찬가지입니다!

2023-01-26 04:41 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                                fieldWithPath("content[].orderNo").description("주문번호"),
param처리 및 docs에도 param처리 부탁드립니다.

2023-01-26 04:43 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/order/relationship/controller/OrderProductStateCodeControllerTest.java
> +                                fieldWithPath("codeNo").description("주문 상품 상태 코드 번호"),
request 쪽에 path variable이 빠진 것 같습니다.

2023-01-26 04:44 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/order/relationship/controller/OrderProductStateCodeControllerTest.java
> +                );
document 작성부분이 빠진 것 같습니다! 그리고 pathvariable과 param 처리도 부탁드립니다!

2023-01-26 04:45 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/orderstatecode/controller/OrderStateCodeControllerTest.java
> +                        responseFields(
pathvariable 넣어주세여

2023-01-26 04:47 UTC, hobby3530 commented on src/test/java/com/nhnacademy/bookpubshop/orderstatecode/controller/OrderStateCodeControllerTest.java
> +                );
문서 작성부분이 빠진것 같습니다.

2023-01-26 04:51 UTC, hobby3530 requested changes
수고하셨습니다!!

2023-01-26 06:14 UTC, seohyeon07 commented on src/main/java/com/nhnacademy/bookpubshop/order/dto/CreateOrderRequestDto.java
> +    @NotBlank(message = "도로명 주소는 필수 입력사항입니다.")
추가하였습니다.

2023-01-26 06:27 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                        .content(mapper.writeValueAsString(new PageResponse<>(pages))))
네 수정하였습니다.

2023-01-26 06:27 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                        responseFields(
추가하였습니다.

2023-01-26 06:32 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                                                .description("사유 명"),
{
  "productAmounts" : {
    "1" : 3
  }
}
Map 의 필드와 모든 하위 항목을 설명하는 역할입니다.

2023-01-26 06:36 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                ));
수정하였습니다.

2023-01-26 06:51 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                                parameterWithName("orderNo").description("주문 번호"))));
수정하였습니다.

2023-01-26 06:51 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/order/controller/OrderControllerTest.java
> +                                fieldWithPath("content[].orderNo").description("주문번호"),
수정하였습니다.

2023-01-26 06:51 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/order/relationship/controller/OrderProductStateCodeControllerTest.java
> +                                fieldWithPath("codeNo").description("주문 상품 상태 코드 번호"),
수정하였습니다.

2023-01-26 06:51 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/order/relationship/controller/OrderProductStateCodeControllerTest.java
> +                );
수정하였습니다.

2023-01-26 06:51 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/orderstatecode/controller/OrderStateCodeControllerTest.java
> +                        responseFields(
수정하였습니다.

2023-01-26 06:51 UTC, seohyeon07 commented on src/test/java/com/nhnacademy/bookpubshop/orderstatecode/controller/OrderStateCodeControllerTest.java
> +                );
수정하였습니다.

2023-01-26 09:08 UTC, hobby3530 approved these changes
수고하셨습니다!

2023-01-27 04:56 UTC, unhas01 approved these changes
수고하셧습니다.

2023-01-27 05:16 UTC, merged